### ISSUE TITLE
Error: elt id not found

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#80] opened 2018-01-05 18:20 UTC
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-JPKtUSBZxvo

Error: elt id not found
    at mkRec (https://easycaped-1.firebaseapp.com/js/sync.js:56:25)
    at promIdbPutElement (https://easycaped-1.firebaseapp.com/js/sync.js:92:15)
    at updateEltToDoc (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2456:9)
    at setTimeout (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1692:28)

Error source:
* error

Context:
* Version: 0.64.07
* Started: 2018-01-05T14:58
* Now:     2018-01-05T18:19
* Elapsed: 12079.73 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment] 2018-01-06 09:52
@MikeRidgway Thanks. Not sure what is happening. Trying to catch the error earlier (in > 0.64.09).

It would be nice if you could reproduce it again.

**Comment by lborgman** [comment] 2018-01-08 00:51
Closing this because it is a duplicate.

**Closed as completed by lborgman** 2018-01-08 00:51 UTC
Labels: bug
