### ISSUE TITLE
Error: addPunctuation no elt id, aw

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#115] opened 2018-01-19 00:37 UTC
Got this after deleting a word, then going to the next word and then pressing Ctrl+Enter.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-WUg5ud8eM-k

Error: addPunctuation no elt id, aw
    at addPunctuation (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2092:25)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:493:13

Error source:
* error

Context:
* Version: 0.64.44
* Started: 2018-01-19T00:29
* Now:     2018-01-19T00:36
* Elapsed: 411.762 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment] 2018-01-19 02:13
@MikeRidgway  Thanks, not easy to reproduce, but I think I know what the problem is.

**Comment by lborgman** [comment] 2018-01-19 13:05
I hope this is fixed in 0.64.46. But it is rather complicated (due to my efforts to make things work in a mobile with more limited resources).

**Comment by lborgman** [comment] 2018-01-30 04:31
Can you still reproduce it, @MikeRidgway ?

**Comment by lborgman** [comment] 2018-02-01 18:45
I think this was the problem I fixed earlier today so I am closing this. (Fixed in next version, not uploaded yet.)

**Closed as completed by lborgman** 2018-02-01 18:45 UTC
Labels: bug
