### ISSUE TITLE
 Error: addPunctuation no elt id, w1

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#129] opened 2018-02-01 01:18 UTC
Pressing Ctrl+Enter in non word-edit mode on the first word in about the third line.
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-CYM40HN82l4

Error: addPunctuation no elt id, w1
    at doIt (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2156:33)
    at https://easycaped-1.firebaseapp.com/js/caped-editor.js:2133:13
    at <anonymous>

Error source:
* unhandledrejection

Context:
* Version: 0.64.62
* Started: 2018-02-01T01:15
* Now:     2018-02-01T01:16
* Elapsed: 107.078 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment] 2018-02-01 13:46
Thanks @MikeRidgway , I thought I had fixed this. Unfortunately I can't find what is wrong right now. I can't reproduce it. 

I have put in a slightly better error message in the next version. Please report the new error if you see this problem again. Or, perhaps "when you see it...".

(BTW I want OK from you before I upload the new version. It might break old data, I am not sure.)

**Comment by lborgman** [comment] 2018-02-01 14:38
Ah, found it. The "play arrow", of course. Forgot to check at one point. Fixed in next release.

**Closed as completed by lborgman** 2018-02-01 14:38 UTC
Labels: bug
