### ISSUE TITLE
Error in version 0.64

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#42] opened 2018-01-03 21:42 UTC
This error occurred while clicking between the second right most and third right most buttons. Reset to original and Previous change.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-wGSB8P1wl1g

TypeError: Cannot read property 'substr' of undefined
    at capitalizeWord (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1576:19)
    at HTMLDivElement.<anonymous> (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1423:17)

Context:
* Error source: error
* 2018-01-03T21:40
* Version: 0.64
* Symbol(local)
* Logged in

**Comment by lborgman** [comment] 2018-01-04 00:50
Thanks Mike. Looks like a Duplicate of #48

**Comment by lborgman** [comment] 2018-01-31 20:12
Closing because the info is not useful any more (since the code has changed). Please report again if you see the problem.

**Closed as completed by lborgman** 2018-01-31 20:12 UTC
Labels: bug
